text_sensor:
  - platform: state_machine
    name: Light Brightness State Machine
    initial_state: OFF
    states:
      - name: OFF
        on_enter:
          - light.turn_off: light1
      - name: ON
        on_enter:
          - light.turn_on:
              id: light1
              brightness: 100%
      - EDITING
    inputs:
      - name: CLICK
        transitions:
          - ON -> OFF
          - OFF -> NO
          - from: EDITING
            to: EDITING
            action: # cycle through brightness levels
              - lambda: |-
                  auto call = id(light1).turn_on();
                  if (id(light1).state > 0.0) {                    
                    call.set_brightness(id(light1).state - 0.1);
                  } else {
                    call.set_brightness(1.0);
                  }
                  call.perform();
      - name: HOLD
        transitions:
          - ON -> EDITING
          - EDITING -> ON

binary_sensor:
  - platform: gpio
    pin: D6
    name: "Button"
    on_click:
      min_length: 50ms
      max_length: 350ms
      then:
      - state_machine.transition: CLICK
    on_multi_click:
    - timing:
        - ON for at most 3s
      then:
        - state_machine.transition: HOLD

light:
  - platform: monochromatic
    name: "Light"
    id: light1
    output: light1_output